# -*- coding: utf-8 -*-
"""studuntperformance_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P5KfFOZ8vuLO8nALRBpX2KUme6aUpfGz
"""

import pandas as pd
df = pd.read_csv("")
df['Total'] = df[['Math', 'Science', 'English']].sum()
df['Average'] = df['Total'] / 3

def assign_grade(avg):
    if avg >= 90:
        return 'A'
    elif avg >= 75:
        return 'B'
    elif avg >= 60:
        return 'C'
    else:
        return 'D'

df['Grade'] = df['Average'].apply(assign_grade)

top_students = df.sort_values(by='Average', ascending=False)

highest_scores = {
    'Math': df['Math'].max(),
    'Science': df['Science'].max(),
    'English': df['English'].max()
}

print("Student Result Analysis")
print(df)

print("\nTop Performers:")
print(top_students[['Name', 'Average']])

print("\nSubject-wise Highest Scores:")
print(highest_scores)

print("\nSummary Statistics:")
print(df.describe())